[project]
name = "{{CODENAME}}"
version = "0.1.0"

authors = []
maintainers = []
description = ""
readme = "README.md"

requires-python = ">=3.13"
dependencies = ["numpy"]

[project.scripts]
{{CODENAME}} = "src.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
