local M = {}

-- :h highlight-groups

-- TODO: :h expr-highlight

M.get = function(c)
  return {
    ColorColumn = 'CursorLine',
    Conceal = 'NonText',
    CurSearch = 'Search',
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = 'Cursor',
    CursorIM = 'Cursor',
    CursorColumn = 'CursorLine',
    CursorLine = { bg = c.ui.cursor_line },
    Directory = { fg = c.misc.directory },
    DiffAdd = { bg = c:dim(c.diff.add, 0.3) },
    DiffChange = { bg = c:dim(c.diff.change, 0.3) },
    DiffDelete = { bg = c:dim(c.diff.delete, 0.3) },
    DiffText = { bg = c:dim(c.diff.change, 0.5) },
    DiffTextAdd = { bg = c:dim(c.diff.add, 0.3) },
    EndOfBuffer = 'NonText',
    TermCursor = 'Cursor',
    OkMsg = { fg = c.diag.ok },
    WarningMsg = { fg = c.diag.warn },
    ErrorMsg = { fg = c.diag.error },
    StderrMsg = { fg = c.diag.error },
    StdoutMsg = {},
    WinSeparator = { fg = c.ui.border },
    Folded = { bg = c.ui.fold_line },
    FoldColumn = {},
    SignColumn = {},
    IncSearch = 'Search',
    Substitute = 'Search',
    LineNr = { fg = c.ui_text.line_number },
    LineNrAbove = 'LineNr',
    LineNrBelow = 'LineNr',
    CursorLineNr = { fg = c.ui_text.status_line, bg = c.ui.cursor_line, bold = true },
    CursorLineFold = 'CursorLine',
    CursorLineSign = 'CursorLine',
    MatchParen = { fg = c.ui_text.guide, bold = true },
    ModeMsg = {},
    MsgArea = 'Normal',
    MsgSeparator = { fg = c.ui.border, strikethrough = true },
    MoreMsg = { fg = c.ui_text.guide, bold = true },
    NonText = { fg = c.ui_text.non_text },
    Normal = { fg = c.fg, bg = c.none },
    NormalFloat = 'Normal',
    FloatBorder = { fg = c.ui.border },
    -- FloatShadow = {},
    -- FloatShadowThrough = {},
    FloatTitle = { fg = c.markup.title, bold = true },
    FloatFooter = { fg = c.markup.footer },
    NormalNC = 'Normal',
    Pmenu = { bg = c.ui.popup },
    PmenuSel = { bg = c.ui.cursor_line },
    -- PmenuKind = {},
    -- PmenuKindSel = {},
    -- PmenuExtra = {},
    -- PmenuExtraSel = {},
    -- PmenuSbar = {},
    -- PmenuThumb = {},
    PmenuMatch = { bold = true },
    PmenuMatchSel = { bold = true },
    PmenuBorder = { fg = c.ui.border },
    -- PmenuShadow = {},
    -- PmenuShadowThrough = {},
    -- ComplMatchIns = {},
    -- PreInsert = {},
    -- ComplHint = {},
    -- ComplHintMore = {},
    Question = { fg = c.ui_text.guide, bold = true },
    QuickFixLine = { bg = c.ui.selection, bold = true },
    Search = { fg = c.bg, bg = c.ui.search },
    SnippetTabstop = 'NonText',
    SnippetTabstopActive = 'NonText',
    SpecialKey = 'NonText',
    SpellBad = { sp = c:dim(c.diag.error, 0.5), undercurl = true },
    SpellCap = { sp = c:dim(c.diag.warn, 0.5), undercurl = true },
    SpellLocal = { sp = c:dim(c.diag.hint, 0.5), undercurl = true },
    SpellRare = { sp = c:dim(c.diag.hint, 0.5), undercurl = true },
    StatusLine = { fg = c.ui_text.status_line, bold = true },
    StatusLineNC = { fg = c.ui_text.status_line },
    StatusLineTerm = 'StatusLine',
    StatusLineTermNC = 'StatusLineNC',
    TabLine = { fg = c.ui_text.tatus_line },
    TabLineFill = 'Normal',
    TabLineSel = { fg = c.fg, bold = true },
    Title = { fg = c.markup.title, bold = true },
    Visual = { bg = c.ui.selection },
    VisualNOS = 'Visual',
    Whitespace = 'NonText',
    -- WildMenu = {},
    WinBar = 'StatusLine',
    WinBarNC = 'StatusLineNc',

    -- Menu = {},
    -- Scrollbar = {},
    -- Tooltip = {},
  }
end

return M
