#!/bin/sh

if tailscale status >/dev/null 2>&1; then
	is_open=1
else
	is_open=0
fi

case $BLOCK_BUTTON in
	3) if [ $is_open -eq 1 ]; then
		doas tailscale down
	else
		doas tailscale up
	fi ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if [ $is_open -eq 1 ]; then
	printf '󰌆 '
else
	printf '󰌊 '
fi
